before_install:
  - sudo aptitude -y -q install curl make libcairo2-dev
  - git clone --depth=1 git://github.com/nddrylliog/rock.git 
  - (cd rock && make -s quick-rescue)
  - export PATH=$PATH:$PWD/rock/bin

script:
  - export OOC_LIBS=$PWD
  - cd samples
  - mkdir -p travis
  - rock -v image-basic.ooc -o=travis/image-basic && travis/image-basic
  - rock -v image-stars.ooc -o=travis/image-stars && travis/image-stars

